### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.
cs.config:
  baseDir: /home/palos/content-server
  processedDir: /home/palos/content-server-done
  delay: 60000
  aINetworkURL: http://9.138.226.41:8111/infer/
  annotationServiceURL: http://branosanot.com/createImage

spring.jmx:
   enabled: false

spring:
  h2.console.enabled: true
  h2.console.path: /h2

  jpa.hibernate.ddl-auto: update

  datasource:
    url: jdbc:h2:file:~/spring-boot-h2-db
    username: sa
    password:
    driverClassName: org.h2.Driver


server:
  port: 8090

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  imageName: content-server
  version: 0.1
  description: boot-example default description

info:
  build:
    artifact: ${project.artifactId}
    imageName: ${project.imageName}
    description: ${project.description}
    version: ${project.version}


---
spring:
  profiles: test

spring.jpa:
    hibernate.ddl-auto: create-drop
